### ISSUE TITLE
seems like nighly broke aster again

### ISSUE THREAD

**Issue by SirVer** [serde-rs/aster#34]
This is on latest nightly, aster 0.4.6. 

rustc 1.5.0-nightly (f93ab64d4 2015-09-21)

```
mac.rs:56:19: 56:40 error: no associated item named `MacInvocTT` found for type `syntax::ast::Mac_` in the current scope
```

**Comment by Manishearth** [comment]
#33 fixes it

**Comment by larsbergstrom** [comment]
This is also blocking https://github.com/servo/skia/pull/72. Can we please land the associated PR? Thanks!

**Comment by erickt** [comment]
I've updated syntex, and just waiting for the #33 tests to go green on travis before merging it in.

**Comment by Manishearth** [comment]
It's green
