### ISSUE TITLE
Build errors with current libsyntax nightly

### ISSUE THREAD

**Issue by tsurai** [serde-rs/aster#38]
A recent [pull request](https://github.com/rust-lang/rust/pull/28642) in rust nightly introduced some changes to libsyntax causing build errors in aster. The ast::Ident constructor now takes two arguments instead of one. I'm not trying to fix this and create a PR because of my inexperience with libsyntax.

rustc 1.5.0-dev (90c04d036 2015-09-27)

**Comment by erickt** [comment]
Aster should be back to building now.
