### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by MarkSwanson** [serde-rs/aster#45]
Just a FYI - aster stopped compiling for me today. I'm not sure why exactly because I didn't use multirust to update my rust environment.

I'm unable to work in Rust atm until I find a workaround.
I should probably be using Cargo.lock better...

I just upgraded to the latest rust nightly-2015-10-27 and I still get errors like:

src/item.rs:473:39: 473:43 error: mismatched types:
 expected `syntax::ast::VariantData`,
    found `syntax::ptr::P<syntax::ast::VariantData>`
(expected enum `syntax::ast::VariantData`,
    found struct `syntax::ptr::P`) [E0308]
src/item.rs:473         let struct_ = ast::ItemStruct(data, self.generics);

etc...

**Comment by Manishearth** [comment]
Opened #46
