### ISSUE TITLE
compile issue with nightly

### ISSUE THREAD

**Issue by emabee** [serde-rs/aster#68]
...\aster-0.13.1\src\item.rs:1350:20: 1357:10 error: missing field `defaultness` in initializer of `syntax::ast::ImplItem` [E0063]
...\aster-0.13.1\src\item.rs:1350         let item = ast::ImplItem {
...\aster-0.13.1\src\item.rs:1351             id: ast::DUMMY_NODE_ID,
...\aster-0.13.1\src\item.rs:1352             ident: self.id,
...\aster-0.13.1\src\item.rs:1353             vis: self.vis,
...\aster-0.13.1\src\item.rs:1354             attrs: self.attrs,
...\aster-0.13.1\src\item.rs:1355             node: node,
...                               ...
...\aster-0.13.1\src\item.rs:1350:20: 1357:10 help: run `rustc --explain E0063` to see a detailed explanation

**Comment by erickt** [comment]
Should be back working in v0.8!

**Comment by emabee** [comment]
That's good news, thanks! But what does it mean in practice? Is v0.8 an internal version of nightly? Am I right that this version is not yet released?

**Comment by Manishearth** [comment]
He means aster 0.14 (0.14.0, to be precise). The crates are published, but they don't have major version numbers yet.

**Comment by emabee** [comment]
issue is fixed, thanks (with aster 0.14.0, which is based on quasi 0.8 (here it is...))

**Comment by erickt** [comment]
Oops yeah. I released many crates yesterday. I forgot what repo this was in :)
