### ISSUE TITLE
type name `ast::StructFieldKind` is undefined or not in scope

### ISSUE THREAD

**Issue by voidxnull** [serde-rs/aster#72]
Getting this error when building with the latest nightly: `rustc 1.9.0-nightly (bf5da36f1 2016-04-06)`

**Comment by KodrAus** [comment]
That'd be because of https://github.com/rust-lang/rust/pull/32682

Looks like it's all just rolled up into `StructField` now

**Comment by KodrAus** [comment]
Unless someone else is on top of this I'll do a PR for this this evening
