### ISSUE TITLE
Breakage with recent nightly

### ISSUE THREAD

**Issue by alexbool** [serde-rs/aster#82]
```
/Users/alexbool/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.17.0/src/mac.rs:112:18: 112:67 error: this function takes 5 parameters but 4 parameters were supplied [E0061]
/Users/alexbool/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.17.0/src/mac.rs:112     let mut cx = ExtCtxt::new(sess, cfg, ecfg, feature_gated_cfgs);
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alexbool/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.17.0/src/mac.rs:112:18: 112:67 help: run `rustc --explain E0061` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
```

```
rustc 1.11.0-nightly (7d2f75a95 2016-06-09)
binary: rustc
commit-hash: 7d2f75a953b5645d3a336b2978b48b60d310bf54
commit-date: 2016-06-09
host: x86_64-apple-darwin
release: 1.11.0-nightly
```

**Comment by KodrAus** [comment]
I had a quick look at this, and it looks like it's due to https://github.com/rust-lang/rust/commit/51499b6e1fd892b68eeb28eaec9031f01a6a9409

@erickt @dtolnay  Is there going to be extra work needed in `syntex` to expose something like the newly public `MacroLoader` in `rustc_metadata`, and will that affect what the `ExtCtxt` does?

**Comment by nubis** [comment]
I gave it a go using the DummyMacroLoader but I closed my pull request because I'm not sure it is what is needed. Maybe someone more experienced with these crates can have a look? #83

**Comment by erickt** [comment]
Syntex v0.34 just came out, which I think contains MacroLoader. I'll see if I can get it working tonight if #83 doesn't do it.

**Comment by KodrAus** [comment]
Keen to see the implementation, I'm not familiar with `MacroLoader` so don't know what it does

**Comment by dtolnay** [comment]
Doesn't look like Syntex 0.34 contains MacroLoader - the libsyntax in 0.34 is from 2016-06-07 while MacroLoader merged on 2016-06-09.

**Comment by alexbool** [comment]
Thanks!
I guess now you also have to push a new serde release?

**Comment by erickt** [comment]
@alexbool: yep! We just released a new `serde_codegen` and `serde_macros`.

**Comment by alexbool** [comment]
Thank you very much!

**Comment by dtolnay** [comment]
@nubis @KodrAus in case you are still curious, here is the fix that Erick ended up making: [syntex/src/lib.rs
](https://github.com/serde-rs/syntex/commit/d914b201e52fac9aa9cfdb4074a00625e003ce59#diff-4279421b340ead27a87b6e2a74c67fea)
