### ISSUE TITLE
0.16 Broken on nightly

### ISSUE THREAD

**Issue by elliottneilclark** [serde-rs/aster#85]
`/Users/elliott/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.17.0/src/mac.rs:112:18: 112:67 error: this function takes 5 parameters but 4 parameters were supplied [E0061]
/Users/elliott/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.17.0/src/mac.rs:112     let mut cx = ExtCtxt::new(sess, cfg, ecfg, feature_gated_cfgs);
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/elliott/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.17.0/src/mac.rs:112:18: 112:67 help: run`rustc --explain E0061`to see a detailed explanation`
## `active toolchain

nightly-x86_64-apple-darwin (default)
rustc 1.11.0-nightly (51d2d3da8 2016-06-12)`

**Comment by dtolnay** [comment]
This is fixed in 0.18. In general we cannot support old versions on nightly because we use its [unstable private API](https://github.com/serde-rs/aster/blob/5677155382b9e3e8df976042c2ebe6a73e61a261/src/lib.rs#L1).
